message: #消息服务
  model: ROCKET_MQ
  rocketmq: 
    namesrvAddr: 192.168.99.100:9876
    producer:
      retrytimes: 10
      producerGroupName: testproducerGroupName1
      #transactionProducerGroupName: testtransactionProducerGroupName
    consumer:
      consumerGroupName: testconsumerGroupName1
      isConsumerBroadcasting: false
      consumerBatchMaxSize: 0
      isEnableOrderConsumer: false
      isEnableHisConsumer: false
